---
- name: Debug
  debug:
    var: nginx_sites.value
- name: Set hostname
  set_fact:
    web_hostname: "{{ nginx_sites.value.web_hostname }}"

- name: Configure nginx
  template:
    src: nginx-site.j2
    dest: "/etc/nginx/sites-available/{{web_hostname}}"

- name: Enabling {{inventory_hostname}} nginx config
  file:
    src: /etc/nginx/sites-available/{{web_hostname}}
    dest: /etc/nginx/sites-enabled/{{web_hostname}}
    state: link

- name: Disable default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
