---
- name: Debug
  debug:
    var: servers.value
- name: Set hostname
  set_fact:
    web_hostname: "{{ servers.value.web_hostname }}"

- name: Configure nginx
  template:
    src: nginx-site.j2
    dest: '/etc/nginx/sites-available/{{web_hostname}}'

- name: Enabling {{inventory_hostname}} nginx config
  file:
    src: /etc/nginx/sites-available/{{web_hostname}}
    dest: /etc/nginx/sites-enabled/{{web_hostname}}
    state: link
