---
- name: Create prometheus group
  group:
    name: prometheus    

- name: Create prometheus user
  user:
    name: prometheus
    state: present
    comment: Prometheus User
    createhome: yes
    groups: prometheus

- name: Create alertmanager directory
  file:
    path: /opt/alertmanager
    state: directory
    owner: prometheus
    group: prometheus

- name: Set alertmanager URL
  set_fact:
    prometheus_url: https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz

- name: Download and unpack
  unarchive:
    src: "{{ prometheus_url }}"
    dest: /opt/alertmanager
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Configure service
  template:
    src: alertmanager.service.j2
    dest: '/etc/systemd/system/alertmanager.service'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Configure service
  template:
    src: alertmanager.yml.j2
    dest: '/opt/alertmanager/alertmanager.yml'
    
- name: Start Alert manager
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: alertmanager

