---
- name: Add Node Config to Prometheus
  template: 
    src: host.j2
    dest: /opt/prometheus/hosts.d/{{ inventory_hostname }}.json
  delegate_to: "{{ monitor_server }}"
  when: monitor_server is defined
