---
- name: Add Node Config to Prometheus
  template: 
    src: host.j2
    dest: /opt/prometheus/hosts.d/{{ inventory_hostname }}.json
  delegate_to: "{{ monitor_server }}"

#- name: Firewall Allow 9100
#  ufw:
#    rule: allow
#    port: 9100
#    proto: tcp
