---
- name: "Set KVM Credentials"
  set_fact:
    proxmox_api_host: "{{proxmox_server[inventory_hostname]['api_host'] }}"
    proxmox_api_password: "{{proxmox_server[inventory_hostname]['api_password'] }}"
    proxmox_api_user: "{{proxmox_server[inventory_hostname]['api_user'] }}"

- name: "Set variables"
  set_fact:
    vmid: "{{ 9000 + template.value.id }}"
    name: "{{ template.key}}"
    vmid_cluster: 0

- name: "Set cluster vmid offest"
  set_fact:
    vmid_cluster: "{{(100 * proxmox_server[inventory_hostname]['id']) | int }}"
    vmid: "{{ 9000 + template.value.id }}"
    name: "{{ template.key}}"
  when: cluster == true
- name: "Set variables"
  set_fact:
    vmid: "{{ (9000 + template.value.id) + vmid_cluster | int }}"
    name: "{{inventory_hostname}}-{{ template.key}}"
  when: cluster == true

- name: Create debian VM
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: "{{vmid}}"
    node: "{{ inventory_hostname }}"
    name: "{{name}}"

    scsihw: virtio-scsi-pci
    scsi:
      scsi0: 'local:1,format=raw'
    ide:
      ide2: 'local:cloudinit,format=qcow2'
    bootdisk: scsi0

    ciuser: sysadmin
    cipassword: password
    net:
      net0: 'virtio,bridge=vmbr0'
    ipconfig:
      ipconfig0: 'ip=127.0.0.9/32'
    vga: std
    cpu: host
    template: yes
    proxmox_default_behavior: no_defaults 
  register: vm_created 

- name: "Download cloud image {{ template.key }}"
  get_url:
    url: "{{ template.value.url }}"
    dest: "/root/{{template.key}}.qcow2"
  when: vm_created.changed and template.value.url is defined

- name: import init disk
  ansible.builtin.command:
    cmd: "qm importdisk {{vmid}} {{template.key}}.qcow2 local --format qcow2"
  when: vm_created.changed
  register: vm_image

- name: Attach base image disk
  ansible.builtin.lineinfile:
    path: "/etc/pve/local/qemu-server/{{vmid}}.conf"
    regexp: '^scsi0:.*'
    line: "scsi0: local:{{vmid}}/vm-{{vmid}}-disk-1.qcow2"
  when: vm_created.changed

- name: Delete unused image disk
  ansible.builtin.lineinfile:
    path: "/etc/pve/local/qemu-server/{{vmid}}.conf"
    regexp: '^unused0:.*'
    state: absent
  when: vm_created.changed