---
- name: "Set KVM Credentials"
  set_fact:
    proxmox_api_host: "{{proxmox_server[inventory_hostname]['api_host'] }}"
    proxmox_api_password: "{{proxmox_server[inventory_hostname]['api_password'] }}"
    proxmox_api_user: "{{proxmox_server[inventory_hostname]['api_user'] }}"

# Debian 10 template
- name: Create debian 10 template
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: 9002
    node: "{{ inventory_hostname }}"
    name: "Debian10"

    scsihw: virtio-scsi-pci
    virtio:
      virtio0: 'local:1,format=raw'
    ide:
      ide2: 'local:cloudinit,format=qcow2'
    bootdisk: virtio0

    ciuser: sysadmin
    cipassword: password
    net:
      net0: 'virtio,bridge=vmbr0'
    ipconfig:
      ipconfig0: 'ip=127.0.0.9/32'
    vga: std
    cpu: host
    template: yes
    proxmox_default_behavior: no_defaults 
  register: vm_created 

- name: Download cloud image Debian10
  get_url:
    url: https://cdimage.debian.org/cdimage/openstack/current-10/debian-10-openstack-amd64.qcow2
    dest: /root/debian10.qcow2
  when: vm_created.changed

- name: import init disk
  ansible.builtin.command:
    cmd: "qm importdisk 9002 /root/debian10.qcow2 local --format qcow2"
  when: vm_created.changed
  register: vm_image

- name: Attach base image disk
  ansible.builtin.lineinfile:
    path: /etc/pve/local/qemu-server/9002.conf
    regexp: '^virtio0:.*'
    line: 'virtio0: local:9002/vm-9002-disk-1.qcow2'
  when: vm_created.changed

- name: Delete unused image disk
  ansible.builtin.lineinfile:
    path: /etc/pve/local/qemu-server/9002.conf
    regexp: '^unused0:.*'
    state: absent
  when: vm_created.changed

# Debian 11 template
- name: Create debian 11 template
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: 9001
    node: "{{ inventory_hostname }}"
    name: "Debian11"

    scsihw: virtio-scsi-pci
    scsi:
      virtio0: 'local:1,format=raw'
    ide:
      ide2: 'local:cloudinit,format=qcow2'
    bootdisk: virtio0

    ciuser: sysadmin
    cipassword: password
    net:
      net0: 'virtio,bridge=vmbr0'
    ipconfig:
      ipconfig0: 'ip=127.0.0.9/32'
    vga: std
    cpu: host
    template: yes
    proxmox_default_behavior: no_defaults     
  register: vm_created 

- name: Download CloudImage Debian11
  get_url:
    url: https://cdimage.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.qcow2
    dest: /root/debian11.qcow2
  when: vm_created.changed

- name: Import Debian11 disk
  ansible.builtin.command:
    cmd: "qm importdisk 9001 /root/debian11.qcow2 local --format qcow2"
  when: vm_created.changed
  register: vm_image

- name: Attach Debian11 disk
  ansible.builtin.lineinfile:
    path: /etc/pve/local/qemu-server/9001.conf
    regexp: '^virtio0:.*'
    line: 'virtio0: local:9001/vm-9001-disk-1.qcow2'
  when: vm_created.changed

- name: Delete unused image disk
  ansible.builtin.lineinfile:
    path: /etc/pve/local/qemu-server/9001.conf
    regexp: '^unused0:.*'
    state: absent
  when: vm_created.changed
