---
# IPv6 rules
- name: Set iptables to ACCEPT
  iptables:
    ip_version: ipv4
    chain: "{{ item }}"
    policy: ACCEPT
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT']

- name: Set ip6tables to ACCEPT
  iptables:
    ip_version: ipv6
    chain: "{{ item }}"
    policy: ACCEPT
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

- name: Flush iptables
  iptables:
    ip_version: ipv4
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT']

- name: Flush ip6tables
  iptables:
    ip_version: ipv6
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

- name: Flush nat iptables
  iptables:
    ip_version: ipv4
    chain: "{{ item }}"
    table: nat
    flush: yes
  ignore_errors: true
  with_items:  [ 'PREROUTING', 'PREROUTING', 'DOCKER' , 'INPUT' , 'OUTPUT']

- name: Flush nat ip6tables
  iptables:
    ip_version: ipv6
    chain: "{{ item }}"
    flush: yes
    table: nat
  ignore_errors: true
  with_items:  [ 'PREROUTING', 'PREROUTING', 'DOCKER' , 'INPUT' , 'OUTPUT']

- name: ip6tables Allow ICMP
  iptables:
    ip_version: ipv6
    chain: INPUT
    protocol: ipv6-icmp
    jump: ACCEPT

- name: iptables Allow ICMP
  iptables:
    ip_version: ipv4
    chain: INPUT
    protocol: icmp
    jump: ACCEPT

- name: iptables Allow ESTABLISHED RELATED
  iptables:
    ip_version: ipv4
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: ip6tables Allow ESTABLISHED RELATED
  iptables:
    ip_version: ipv6
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: iptables Allow all for lo
  iptables:
    ip_version: ipv4
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: ip6tables Allow all for lo
  iptables:
    ip_version: ipv6
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: iptables Allow ports
  iptables:
    ip_version: ipv4
    chain: INPUT
    protocol: "{{ item.protocol | default('tcp') }}"
    destination_port: "{{ item.port }}"
    source: "{{ item.source | default(omit) }}"
    jump: ACCEPT
  with_items: "{{ firewall_ports }}"

- name: ip6tables Allow Ports
  iptables:
    ip_version: ipv6
    chain: INPUT
    protocol: "{{ item.protocol | default('tcp') }}"
    destination_port: "{{ item.port }}"
    source: "{{ item.sourceIPv6  | default(omit) }}"
    jump: ACCEPT
  with_items: "{{ firewall_ports }}"
  when: firewall_ipv6

- name: Set iptables to DROP
  iptables:
    ip_version: ipv4
    chain: INPUT
    jump: DROP

- name: Set last ip6tables to DROP
  iptables:
    ip_version: ipv6
    chain: INPUT
    jump: DROP