---
- name: Install nginx packages
  apt:
    pkg:
      - certbot
      
- name: Set hostname
  set_fact:
    web_hostname: "{{ servers.value.web_hostname }}"

- name: Configure certbot to reload nginx on renew
  ini_file:
    path: /etc/letsencrypt/cli.ini
    section: ''
    option: deploy-hook
    value: 'systemctl reload nginx'
    state: present

- name: Register Let's Encrypt
  command: certbot register --email {{letsencrypt_email}} --agree-tos -n
  args:
    creates: /etc/letsencrypt/accounts

- name: Get Let's Encrypt Cert
  command: certbot certonly --webroot -w /var/www/html/ -d {{web_hostname}} --rsa-key-size 4096
  args:
    creates: /etc/letsencrypt/live/{{web_hostname}}/fullchain.pem
