---
- name: Create nginx SSL directory
  file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    mode: '700'
    state: directory

- name: Generate 4096 bit DH parameters (this may take a long time...)
  shell: openssl dhparam -writerand - 4096 > /etc/ssl/dhparam.pem
  args:
    chdir: /etc/nginx/ssl
    creates: /etc/ssl/dhparam.pem

- include_tasks: ssl.yml
  loop: "{{ servers | dict2items  }}"
  loop_control:
    loop_var: servers
