---
- name: Create nginx SSL directory
  file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    mode: "700"
    state: directory

- name: Download DH params
  ansible.builtin.get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /etc/ssl/dhparam.pem
    mode: 0644

- include_tasks: ssl.yml
  when: nginx_sites.value.ssl_provider is defined
  loop: "{{ nginx_sites | dict2items  }}"
  loop_control:
    loop_var: nginx_sites
