---
- name: Upgrade the system
  apt:
    update_cache: true
    upgrade: dist
  register: apt_cache
  retries: 50
  until: apt_cache is success
  when: setup_upgrade == true

- name: Install system packages
  apt:
    pkg:
      - ntp
      - python3
      - python3-pip
      - python3-apt
      - vim-nox
      - curl
      - apt-transport-https
      - software-properties-common
      - haveged
      - wget

- name: Install common diagnostic tools
  apt:
    state: present
    pkg:
      - htop
      - mtr-tiny
      - sendmail
      - mailutils
  when: setup_basic == true

- name: Install common build utils
  apt:
    pkg:
      - git
      - build-essential
  when: setup_build == true

- name: Set timezone
  timezone:
    name: "{{ setup_timezone }}"
  when: setup_timezone is defined

- name: Disable predictable network interface naming - Rules
  ansible.builtin.file:
    path: /etc/udev/rules.d/80-net-setup-link.rules
    state: touch
  when: setup_disable_predictable_network

- name: Disable predictable network interface naming - Grub ifnames
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames)\"[^\"]+)(\".*)'
    line: '\1 net.ifnames=0\2'
  when: setup_disable_predictable_network
  register: grub1

- name: Disable predictable network interface naming - Grub biosdevname
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname)\"[^\"]+)(\".*)'
    line: '\1 biosdevname=0\2'
  when: setup_disable_predictable_network
  register: grub2

- name: Enable predictable network interface naming
  ansible.builtin.file:
    path: /etc/udev/rules.d/80-net-setup-link.rules
    state: absent
  when: setup_disable_predictable_network == false

- name: Update grub if changes made
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub1.changed or grub2.changed

# Security
- name: Disable TCP Timestamp
  ansible.posix.sysctl:
    name: net.ipv4.tcp_timestamps
    value: "0"
    sysctl_set: yes
  when: setup_tcp_timestamps == true
