---
- name: Install parted
  apt:
    pkg:
      - parted

- name: debug
  debug:
    var: provision_disk.value.label
- name: Create a new ext4 primary partition /dev/{{provision_disk.key}}
  community.general.parted:
    device: "/dev/{{provision_disk.key}}"
    number: 1
    state: present
    fs_type: ext4

- name: Format /dev/{{provision_disk.key}}
  filesystem:
     fstype: ext4
     dev: "/dev/{{provision_disk.key}}1"
     resizefs: true

- name: Creates directory {{ provision_disk.value.mount_point }}
  file:
    path: "{{ provision_disk.value.mount_point }}"
    state: directory    

- name: Mount up device Live - /dev/{{provision_disk.key}}
  ansible.posix.mount:
    path: "{{ provision_disk.value.mount_point }}"
    src: "/dev/{{provision_disk.key}}"
    fstype: ext4
    state: mounted

- name: Mount up device fstab - /dev/{{provision_disk.key}}
  ansible.posix.mount:
    path: "{{ provision_disk.value.mount_point }}"
    src: "/dev/{{provision_disk.key}}"
    fstype: ext4
    state: present
  when: provision_disk.value.label is not defined

- name: Setting ext label
  shell: "e2label /dev/{{provision_disk.key}} {{provision_disk.value.label}}"
  when: provision_disk.value.label is defined

- name: Mount up device fstab - Label
  ansible.posix.mount:
    path: "{{ provision_disk.value.mount_point }}"
    src: "LABEL={{provision_disk.value.label}}"
    fstype: ext4
    state: present
  when: provision_disk.value.label is defined

